import pytest
from unittest.mock import AsyncMock, patch
from src.controllers.generator import generate_skeleton
from src.models import MCPRequest

@pytest.mark.asyncio
async def test_generate_skeleton_success():
    # Mock response from LLM
    mock_json = """
    {
        "stage": "skeleton",
        "code": "contract MockDAO { }",
        "notes": "Generated by Mock"
    }
    """
    
    # Mock the LLM Provider
    mock_provider = AsyncMock()
    mock_provider.complete.return_value = mock_json
    
    # Patch the Factory to return our mock provider
    with patch("src.services.llm.factory.LLMFactory.get_provider", return_value=mock_provider):
        req = MCPRequest(
            request_id="test-gen-1",
            action="generate",
            payload={"user_request": "Create a token contract"}
        )
        
        response = await generate_skeleton(req)
        
        assert response["request_id"] == "test-gen-1"
        assert response["type"] == "skeleton"
        data = response["data"]
        assert data["stage"] == "skeleton"
        assert data["code"] == "contract MockDAO { }"

@pytest.mark.asyncio
async def test_generate_skeleton_failure():
    # Mock failure
    mock_provider = AsyncMock()
    mock_provider.complete.side_effect = Exception("API Error")
    
    with patch("src.services.llm.factory.LLMFactory.get_provider", return_value=mock_provider):
        req = MCPRequest(
            request_id="test-gen-2",
            action="generate",
            payload={"user_request": "Fail me"}
        )
        
        response = await generate_skeleton(req)
        
        assert response["type"] == "error"
        assert response["error"]["code"] == "GENERATION_FAILED"
